spring:
  profiles:
    active: home
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    hikari:
      jdbcUrl: jdbc:mysql://localhost:3306/one?useSSL=false
      username: root
      password: redhat
      driver-class-name: com.mysql.cj.jdbc.Driver
    second-hikari:
      jdbcUrl: jdbc:mysql://localhost:3306/two?useSSL=false
      username: root
      password: redhat
      driver-class-name: com.mysql.cj.jdbc.Driver


---
spring:
  profiles: home
  datasource:
    hikari:
      jdbcUrl: jdbc:mysql://192.168.1.231:3306/one?useSSL=false
    second-hikari:
      jdbcUrl: jdbc:mysql://192.168.1.231:3306/two?useSSL=false
