spring:
  profiles:
    active: pc
  datasource:
    hikari:
      username: root
      password: redhat
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/one?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    second-hikari:
      username: root
      password: redhat
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/two?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 命名文档块1
---
spring:
  profiles: pc
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://192.168.1.231:3306/one?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    second-hikari:
      jdbc-url: jdbc:mysql://192.168.1.231:3306/two?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
