spring:
  profiles:
    active: default
  datasource:
    initialization-mode: always
    druid:
      url: jdbc:mysql://localhost:3306/common?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
      username: root
      password: redhat
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true


# 命名文档块1
---
spring:
  profiles: pc
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.231:3306/common?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai