spring:
  datasource:
    url: jdbc:h2:mem:testdb
  redis:
    host: 127.0.0.1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
